#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI1 --mode 1920x1080 --rate 120 --pos 1280x0 --primary
xrandr --newmode  "1280x720_60.00"   74.50  1280 1344 1472 1664  720 723 728 748 -hsync +vsync
xrandr --addmode eDP1 "1280x720_60.00"
xrandr --output eDP1 --mode 1280x720_60.00 --pos 0x360


xrdb -merge $HOME/.Xresources
~/.config/polybar/scripts/launch.sh &
tee /sys/class/backlight/intel_backlight/brightness < $HOME/.bg > /dev/null
numlockx on &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3 
bspc config window_gap          0
bspc config focused_border_color "#FF1F00"
bspc config normal_border_color "#595959"
bspc config borderless_monocle false
bspc config single_monocle false


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config focus_by_distance true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol-qt state=tiling
