#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb -merge $HOME/.Xresources &
~/.config/polybar/scripts/launch.sh &
tee /sys/class/backlight/intel_backlight/brightness < root/.bg > /dev/null &
numlockx on &
feh --bg-scale ~/oboi.png &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        3 
bspc config window_gap          0
bspc config focused_border_color "#12FC00"
bspc config normal_border_color "#595959"
bspc config borderless_monocle false
bspc config single_monocle false


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config focus_by_distance true
