[colors]
background = #000000
foreground = #ffffff
primary = #fc00ef
alert = #f53c3c
charging = #26a65b

[bar/main]
monitor = ${env:MONITOR:}
width = 100%
height = 24pt
background = ${colors.background}
foreground = ${colors.foreground}

# Исправляем наезжание модулей
fixed-center = true
padding-left = 0
padding-right = 0
module-margin = 0
line-size = 10
padding-top = 0
padding-bottom = 0

# 1. Пиксельный шрифт для текста
font-0 = "terminus-font:bold:size=18;2"
# 2. Nerd Font для иконок батареи/вайфая
font-1 = "Symbols Nerd Font:size=12;3"

modules-left = launcher sep xwindow
modules-right = tray sep color sep power sep network sep bg sep gromkost sep xkeyboard sep battery sep date sep time sep1

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
wm-restack = bspwm

[module/sep]
type = custom/text
content = "%{O3}"
content-background = #FF1F00
content-padding = 0
margin = 0
content-margin = 5pt

[module/sep1]
type = custom/text
content = "%{O3}"
content-padding = 0
margin = 0
content-margin = 3pt

[module/launcher]
type = custom/text
format = " "
click-left = rofi -show drun -show-icons

[module/power]
type = custom/text
format = "󰤆"
click-left = ~/.config/rofi/rofi-power.sh

[module/xwindow]
type = internal/xwindow
label = "%title%"
label-maxlen = 80

[module/network]
type = custom/text
format = ""
click-left = xterm -T "Wi-Fi" -e sudo ~/wifi.sh
[module/bg]
type = custom/text
format = ""
click-left = xterm -T "RpkocTb" -e ~/bg.sh

[module/gromkost]
type = custom/text
format = ""
click-left = GSK_RENDERER=cairo GTK_THEME=Adwaita:dark pavucontrol

[module/color]
type = custom/text
format = ""
click-left = ~/color.sh

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format = <label-layout>
label-layout = %icon%
layout-icon-0 = us;ENG
layout-icon-1 = ru;РУС

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 100
low-at = 15
format-charging =  <ramp-capacity> <label-charging>
label-charging = "%percentage%%"

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = "%percentage%%"

format-full = <ramp-capacity> <label-full>
label-full = "%percentage%%"

format-low = <ramp-capacity> <label-low>
format-low-background = ${colors.alert}
label-low = "%percentage%%"

ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁽
ramp-capacity-2 = 󰁿
ramp-capacity-3 = 󰂂
ramp-capacity-4 = 󰁹

[module/date]
type = custom/script
exec = ~/.config/polybar/scripts/date.sh
interval = 60
label = %output%

[module/time]
type = internal/date
interval = 60
time = %H:%M
label = %time%

[module/tray]
type = internal/tray
tray-spacing = 7px
tray-size = 18px
